### ISSUE TITLE
Add Movie Watch Providers endpoint

### ISSUE THREAD

**Issue by se1exin** [andywampir/node-themoviedb#11]
Hey 👋 thanks for open sourcing this library!

Just wondering if you had any plans on adding the 'Watch Providers' endpoint? https://developers.themoviedb.org/3/movies/get-movie-watch-providers

**Comment by andywampir** [comment]
Hi, I'm currently working on a new version of this module, and in a new version I'm planning add all endpoints that not added in current version.
New version also will be include endpoints v4 and better usage experience.

**Comment by andywampir** [comment]
If I will had more time I'll add endpoints in current version

**Comment by se1exin** [comment]
Hey thanks for the info @andywampir. Don't make extra work for yourself - looking forward to the new version 😁
