### ISSUE TITLE
Can you build this for NPM?

### ISSUE THREAD

**Issue by markhoney** [andywampir/node-themoviedb#2]
The NPM package for this repo appears to just contain a Typescript file, and no compiled Javascript. Are you able to add a compile script, so that I can use the NPM package with Javascript?

Thanks!

**Comment by andywampir** [comment]
I'm so sorry that i didn't build for NPM.
Now it's done.

Note: now in response object excluded property `rateLimit` ([details](https://developers.themoviedb.org/3/getting-started/request-rate-limiting))
