### ISSUE TITLE
Cannot destructure property 'body' of options

### ISSUE THREAD

**Issue by boydaihungst** [andywampir/node-themoviedb#4]
I got this error when using a function that does not require args like `Genre.getMovieList`. 
Please update the `createEndpoints.ts` file. Many thanks.
<img src="https://i.ibb.co/St7SHyb/Screenshot-20200607-002638.png" alt="Example of uploading image to GitHub's CDN" width="500px">

**Comment by andywampir** [comment]
Please check if it works with `0.2.3`

**Comment by boydaihungst** [comment]
it worked now with `0.2.3` version.
