### ISSUE TITLE
NotFoundError

### ISSUE THREAD

**Issue by boulosda** [andywampir/node-themoviedb#5]
Seems like the 0.2.3 has some breaking changes, from first glance it looks like it may be due to the update that removed slashes from endpoints. For now using 0.2.2 works as expected so far.

I haven't tested if all endpoints are broken in 0.2.3 but the README example is not working as expected.

**Comment by andywampir** [comment]
Please check if it error is disappeared in `v0.2.4`

**Comment by boulosda** [comment]
Thank you for the update, its looking good in v0.2.4. I'll go ahead and close this.
