### ISSUE TITLE
Bug: Wording in type definitions for GetSimilarTVShows 

### ISSUE THREAD

**Issue by xXanth0s** [andywampir/node-themoviedb#7]
There is a wording in the type definitions. Unfortunately I cannot create a PR.
The variable `results` is wrong spelled.

**Current Situation:**
```typescript
interface GetSimilarTVShows extends ResponseWithPage {
    resulst: Objects.TVShow[];
}
```

**Expected:**
```typescript
interface GetSimilarTVShows extends ResponseWithPage {
   results: Objects.TVShow[];
}
```

**Comment by andywampir** [comment]
Fixed in [v0.2.6](https://github.com/andywampir/node-themoviedb/releases/tag/v0.2.6)
