### ISSUE TITLE
Bug: cannot fetch data from [tv.episode.getDetails]

### ISSUE THREAD

**Issue by AdamHavlicek** [andywampir/node-themoviedb#8]
I dunno but the function only returns promise rejection with 404 even though passed args are correct one. When I looked into debugger it sends request to unformatted href.

![2021-01-26_08-32](https://user-images.githubusercontent.com/50631920/105814036-0a349380-5fb1-11eb-88e5-c0be795d1e38.png)

**Comment by andywampir** [comment]
Can you please show args, which you passed in function?

**Comment by AdamHavlicek** [comment]
yeah I can provide them to you.
![2021-01-26_09-48](https://user-images.githubusercontent.com/50631920/105821871-a06db700-5fbb-11eb-80db-768fc611e3d8.png)

**Comment by andywampir** [comment]
Should be fixed in `v0.2.7`
Please update, if it fixed please close this issue.
